name: Release

on:
  push: 
    branches: ["dev"]

jobs:
  release:
    runs-on: ubuntu-latest
    stesp:
      - name: "checkout"
        uses: "actions/checkout@v3"
      - name: Python Semantic Release
        id: semrelease
        uses: python-semantic-release/python-semantic-release@v9.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
